### ISSUE TITLE
Fix style binding warnings

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/ember-content-kit#16]
> WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.

Repair these.

**Comment by bantic** [comment]
@mixonic Are these from somewhere else? I don't think we bind style attributes in ember-content-kit. I don't see these warnings when running tests on master, fwiw.

**Comment by mixonic** [comment]
ah damn. I meant to put this on `ember-sticky-wicket`

https://github.com/bustlelabs/ember-sticky-wicket/blob/master/tests/dummy/app/templates/sticky-item.hbs#L2
