### ISSUE TITLE
Warning: ignoring input sourcemap...

### ISSUE THREAD

**Issue by rlivsey** [bustlelabs/ember-content-kit#19]
I get the following warning when using the addon:

Warning: ignoring input sourcemap for vendor/content-kit-editor/global/content-kit-editor.js because ENOENT: no such file or directory, open '[path-to-app]/tmp/concat_with_maps-input_base_path-Cd3L4EPZ.tmp/0/vendor/content-kit-editor/global/content-kit-editor.map'

Could this be to do with the way the files are [copied over from `content-kit-editor`][1]? 
Does `content-kit-editor` build a source map for this to use?

[1]: https://github.com/bustlelabs/ember-content-kit/blob/a3bda6765dee23e91ebfd965d45332b1d357248f/index.js#L8-L15

**Comment by mixonic** [comment]
I don't believe builds a source map /cc @bantic

**Comment by bantic** [comment]
content-kit-editor is published with a sourcemap in `dist/global/cotnent-kit-editor.map`. And yes, I think you're right, @rlivsey. I can take a look at this later. If adding the map file works for you I'd happily take a PR, too. :)
