### ISSUE TITLE
Best way to setup mobiledoc structure

### ISSUE THREAD

**Issue by patrickberkeley** [bustlelabs/ember-content-kit#3]
Mobiledoc format seems awesome, but I'm not sure how to bind it to model attributes in ember.

Is the recommended approach to:

1. Bootstrap mobiledoc attributes on the server with the base mobiledoc structure
2. Somehow bind and update the content within that attribute as it's updated in the UI
3. Persist the entire blob of mobiledoc with the update content and tags

If so, will you post an example of binding an ember model attribute's content *within* a mobiledoc blob?

*Again, I realize this library is WIP, so I'd understand if your answer is to just say 'hold off until a future version'*

**Comment by mixonic** [comment]
@patrickberkeley we are definitely in WIP mode- especially this repo.

The mobiledoc object should be converted to a JSON string and persisted as such. The editor should already boot without needing a mobiledoc to exist.

> Persist the entire blob of mobiledoc with the update content and tags

> an example of binding an ember model attribute's content within a mobiledoc blob?

I'm very confused as to what you are trying do achieve here. Mobiledoc should be stored as a string attribute of a model.

**Comment by patrickberkeley** [comment]
Hum okay. I'm probably doing something wrong. I think what you're saying is I shouldn't need to worry about the structure of the mobiledoc content at all; I can just set a value on the editor and persist whatever mobiledoc content it pumps out.

I've been basing what I try out off the integration tests.

component.hbs
```
    {{#content-kit-editor mobiledoc=mobileDoc on-change=(action 'onChange') as |contentKit|}}
        <button {{action contentKit.toggleMarkup 'strong'}}>B</button>
        <button {{action contentKit.toggleMarkup 'em'}}>I</button>
        <button {{action contentKit.toggleLink}}>Link</button>
      {{/content-kit-editor}}
```
component.js
```
  mobileDoc: function() {
    return {
      version: '0.2.0',
      sections: [
        [],
        [
          [1, 'p', [
            [[], 0, this.get('my-model-prop')]
          ]]
        ]
      ]
    };
  }.property('my-model-prop'),
```

I'll give this another shot without messing with mobiledoc setup/structure at all.

**Comment by mixonic** [comment]
@patrickberkeley Ah, yeah you should never need to touch the mobiledoc itself. Never. It is just a file format, like passing an XML document around.

**Comment by patrickberkeley** [comment]
:+1: Makes sense.

**Comment by mixonic** [comment]
@patrickberkeley I'm going to close this. Feel free to ping me here or in the [gitter chat](https://gitter.im/bustlelabs/content-kit-editor) if you have further questions.

**Comment by patrickberkeley** [comment]
:+1: thanks @mixonic
